# Generated by Django 3.2.8 on 2022-05-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20220411_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='event',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='gallery',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('priority',), 'verbose_name': 'Events Information Table'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('priority',), 'verbose_name': 'Galleries Information Table'},
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
