# Generated by Django 3.2.8 on 2022-05-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museum',
            options={'ordering': ('priority',), 'verbose_name': 'Museums Information Table'},
        ),
        migrations.AlterModelOptions(
            name='museumarticles',
            options={'ordering': ('priority',), 'verbose_name': 'Museum Articles Information Table'},
        ),
        migrations.AlterModelOptions(
            name='museumevent',
            options={'ordering': ('priority',), 'verbose_name': 'Museum Events Information Table'},
        ),
        migrations.AlterModelOptions(
            name='museumpieces',
            options={'ordering': ('priority',), 'verbose_name': 'Museum Pieces (artworks) Information Table'},
        ),
    ]
