# Generated by Django 3.2.8 on 2022-03-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('ART', 'Artist'), ('BUY', 'Buyer'), ('ANO', 'Anonymous User'), ('ADM', 'Administrator')], max_length=4),
        ),
        migrations.CreateModel(
            name='WebConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('paramname', models.CharField(max_length=255)),
                ('paramvalue', models.TextField()),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('adminuser', models.ForeignKey(db_column='userid_id', on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'verbose_name': 'Website Configuration Information',
                'db_table': 'webconfig',
            },
        ),
    ]
