# Generated by Django 3.2.8 on 2022-04-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20220313_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('textvalue', models.TextField()),
                ('imagepath', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Carousel Information',
                'db_table': 'carousel',
                'ordering': ('-edited', '-priority'),
            },
        ),
        migrations.AlterField(
            model_name='webconfig',
            name='adminuser',
            field=models.ForeignKey(db_column='adminuser_id', on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
