# Generated by Django 3.2.8 on 2022-05-11 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_auto_20220411_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='data_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carousel',
            name='datatype',
            field=models.CharField(default='Artist', max_length=200),
        ),
        migrations.AlterField(
            model_name='webconfig',
            name='adminuser',
            field=models.ForeignKey(db_column='adminuser_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
