# Generated by Django 3.2.8 on 2022-05-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionhouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionhouse',
            options={'ordering': ('priority',), 'verbose_name': 'Auction House Information Table'},
        ),
        migrations.RemoveField(
            model_name='auctionhouse',
            name='coverimage',
        ),
        migrations.RemoveField(
            model_name='auctionhouse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auctionhouse',
            name='housetype',
        ),
        migrations.AddField(
            model_name='auctionhouse',
            name='country',
            field=models.CharField(blank=True, db_column='cah_auction_house_country', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='auctionhouse',
            name='currency',
            field=models.CharField(blank=True, db_column='cah_auction_house_currency_code', default='', max_length=4),
        ),
        migrations.AddField(
            model_name='auctionhouse',
            name='editedby',
            field=models.CharField(blank=True, db_column='cah_auction_house_record_updatedby', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='auctionhouse',
            name='insertedby',
            field=models.CharField(blank=True, db_column='cah_auction_house_record_createdby', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='auctionhouse',
            name='edited',
            field=models.DateTimeField(auto_now=True, db_column='cah_auction_house_record_updated'),
        ),
        migrations.AlterField(
            model_name='auctionhouse',
            name='housename',
            field=models.CharField(blank=True, db_column='cah_auction_house_name', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='auctionhouse',
            name='houseurl',
            field=models.TextField(db_column='cah_auction_house_website'),
        ),
        migrations.AlterField(
            model_name='auctionhouse',
            name='id',
            field=models.IntegerField(db_column='cah_auction_house_ID', default=None, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='auctionhouse',
            name='inserted',
            field=models.DateTimeField(auto_now_add=True, db_column='cah_auction_house_record_created'),
        ),
        migrations.AlterField(
            model_name='auctionhouse',
            name='location',
            field=models.CharField(blank=True, db_column='cah_auction_house_location', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='auctionhouse',
            name='priority',
            field=models.IntegerField(db_column='cah_auction_house_priority', default=0),
        ),
        migrations.AlterModelTable(
            name='auctionhouse',
            table='core_auction_houses',
        ),
    ]
