# Generated by Django 3.2.8 on 2022-04-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionname', models.TextField()),
                ('auctionid', models.CharField(blank=True, default='', max_length=100)),
                ('auctionhouse', models.CharField(blank=True, default='', max_length=200)),
                ('auctionlocation', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('auctionurl', models.TextField()),
                ('lotslistingurl', models.TextField()),
                ('coverimage', models.TextField()),
                ('auctiontype', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auctions Information Table',
                'db_table': 'auctions',
                'ordering': ('-priority',),
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotid', models.CharField(blank=True, default='', max_length=100)),
                ('lottitle', models.TextField()),
                ('lotdescription', models.TextField()),
                ('artistname', models.TextField()),
                ('artistbirth', models.CharField(blank=True, default='', max_length=50)),
                ('artistdeath', models.CharField(blank=True, default='', max_length=50)),
                ('artistnationality', models.CharField(blank=True, default='', max_length=100)),
                ('medium', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.CharField(blank=True, default='', max_length=200)),
                ('loturl', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('estimate', models.CharField(blank=True, default='', max_length=100)),
                ('soldprice', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('provenance', models.TextField()),
                ('literature', models.TextField()),
                ('exhibited', models.TextField()),
                ('lotimage1', models.TextField()),
                ('lotimage2', models.TextField()),
                ('lotimage3', models.TextField()),
                ('lotimage4', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
            ],
            options={
                'verbose_name': 'Lots (Artworks) Information Table',
                'db_table': 'lots',
                'ordering': ('-priority',),
            },
        ),
    ]
