# Generated by Django 3.2.8 on 2022-05-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ('priority',), 'verbose_name': 'Auctions Information Table'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ('priority',), 'verbose_name': 'Lots (Artworks) Information Table'},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='auctionhouse',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='auctionlocation',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='auctiontype',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='lotslistingurl',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='artistbirth',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='artistdeath',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='artistname',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='artistnationality',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='exhibited',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='literature',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='lotdescription',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='lottitle',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='loturl',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='size',
        ),
        migrations.AddField(
            model_name='auction',
            name='auctionenddate',
            field=models.DateTimeField(blank=True, db_column='faac_auction_end_date', default=None),
        ),
        migrations.AddField(
            model_name='auction',
            name='auctionhouse_id',
            field=models.IntegerField(db_column='faac_auction_house_ID', default=None),
        ),
        migrations.AddField(
            model_name='auction',
            name='auctionstartdate',
            field=models.DateTimeField(blank=True, db_column='faac_auction_start_date', default=None),
        ),
        migrations.AddField(
            model_name='auction',
            name='editedby',
            field=models.CharField(db_column='faac_auction_record_updatedby', default='', max_length=25),
        ),
        migrations.AddField(
            model_name='auction',
            name='insertedby',
            field=models.CharField(db_column='faac_auction_record_createdby', default='', max_length=25),
        ),
        migrations.AddField(
            model_name='auction',
            name='lotcount',
            field=models.IntegerField(db_column='faac_auction_lot_count', default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='published',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], db_column='faac_auction_published', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lot',
            name='artwork_id',
            field=models.IntegerField(db_column='fal_artwork_ID', default=None),
        ),
        migrations.AddField(
            model_name='lot',
            name='auction_id',
            field=models.IntegerField(db_column='fal_auction_ID', default=None),
        ),
        migrations.AddField(
            model_name='lot',
            name='condition',
            field=models.TextField(db_column='fal_lot_condition', default=''),
        ),
        migrations.AddField(
            model_name='lot',
            name='depth',
            field=models.DecimalField(db_column='fal_lot_depth', decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='lot',
            name='editedby',
            field=models.CharField(db_column='fal_lot_record_updatedby', default='', max_length=25),
        ),
        migrations.AddField(
            model_name='lot',
            name='height',
            field=models.DecimalField(db_column='fal_lot_height', decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='lot',
            name='highestimate',
            field=models.DecimalField(db_column='fal_lot_high_estimate', decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='lot',
            name='highestimateUSD',
            field=models.DecimalField(db_column='fal_lot_high_estimate_USD', decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='lot',
            name='insertedby',
            field=models.CharField(db_column='fal_lot_record_createdby', default='', max_length=25),
        ),
        migrations.AddField(
            model_name='lot',
            name='lotimage5',
            field=models.TextField(db_column='fal_lot_image5', default=''),
        ),
        migrations.AddField(
            model_name='lot',
            name='lowestimate',
            field=models.DecimalField(db_column='fal_lot_low_estimate', decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='lot',
            name='lowestimateUSD',
            field=models.DecimalField(db_column='fal_lot_low_estimate_USD', decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='lot',
            name='measureunit',
            field=models.CharField(db_column='fal_lot_measurement_unit', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lot',
            name='pricetype',
            field=models.CharField(blank=True, choices=[('hammer', 'hammer'), ('premium', 'premium')], db_column='fal_lot_price_type', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='published',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], db_column='fal_lot_published', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='saledate',
            field=models.DateTimeField(blank=True, db_column='fal_lot_sale_date', default=None),
        ),
        migrations.AddField(
            model_name='lot',
            name='sizedetails',
            field=models.CharField(blank=True, db_column='fal_lot_size_details', default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lot',
            name='soldpriceUSD',
            field=models.DecimalField(db_column='fal_lot_sale_price_USD', decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='lot',
            name='source',
            field=models.TextField(db_column='fal_lot_source', default=''),
        ),
        migrations.AddField(
            model_name='lot',
            name='status',
            field=models.CharField(blank=True, choices=[('yet to be sold', 'yet to be sold'), ('sold', 'sold'), ('bought-in', 'bought-in'), ('withdrawn', 'withdrawn')], db_column='fal_lot_status', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='sublotid',
            field=models.CharField(blank=True, db_column='fal_sub_lot_no', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lot',
            name='width',
            field=models.DecimalField(db_column='fal_lot_width', decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctionid',
            field=models.CharField(blank=True, db_column='faac_auction_sale_code', default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctionname',
            field=models.TextField(db_column='faac_auction_title'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctionurl',
            field=models.TextField(db_column='faac_auction_source'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='coverimage',
            field=models.TextField(db_column='faac_auction_image'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='edited',
            field=models.DateTimeField(auto_now=True, db_column='faac_auction_record_updated'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='id',
            field=models.IntegerField(db_column='faac_auction_ID', default=None, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='inserted',
            field=models.DateTimeField(auto_now_add=True, db_column='faac_auction_record_created'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='priority',
            field=models.IntegerField(db_column='faac_auction_priority', default=5),
        ),
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.CharField(blank=True, db_column='fal_lot_category', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lot',
            name='edited',
            field=models.DateTimeField(auto_now=True, db_column='fal_lot_record_updated'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='id',
            field=models.IntegerField(db_column='fal_lot_ID', default=None, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='inserted',
            field=models.DateTimeField(auto_now_add=True, db_column='fal_lot_record_created'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lotid',
            field=models.IntegerField(db_column='fal_lot_no'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lotimage1',
            field=models.TextField(db_column='fal_lot_image1', default=''),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lotimage2',
            field=models.TextField(db_column='fal_lot_image2', default=''),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lotimage3',
            field=models.TextField(db_column='fal_lot_image3', default=''),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lotimage4',
            field=models.TextField(db_column='fal_lot_image4', default=''),
        ),
        migrations.AlterField(
            model_name='lot',
            name='medium',
            field=models.CharField(blank=True, db_column='fal_lot_material', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lot',
            name='priority',
            field=models.IntegerField(db_column='fal_lot_priority', default=5),
        ),
        migrations.AlterField(
            model_name='lot',
            name='provenance',
            field=models.TextField(db_column='fal_lot_provenance'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='soldprice',
            field=models.DecimalField(db_column='fal_lot_sale_price', decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AlterModelTable(
            name='auction',
            table='fineart_auction_calendar',
        ),
        migrations.AlterModelTable(
            name='lot',
            table='fineart_lots',
        ),
    ]
