# Generated by Django 3.2.8 on 2022-05-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.IntegerField(blank=True, default=None, null=True)),
                ('totalsoldprice', models.DecimalField(decimal_places=2, max_digits=13)),
                ('artist_name', models.CharField(max_length=255)),
                ('prefix', models.CharField(blank=True, max_length=25)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('birthyear', models.CharField(blank=True, max_length=10, null=True)),
                ('deathyear', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField()),
                ('aka', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField()),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('artistimage', models.TextField()),
            ],
            options={
                'verbose_name': 'Featured Artists Information Table',
                'db_table': 'fa_featured_artists',
            },
        ),
        migrations.CreateModel(
            name='LotArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.IntegerField(blank=True, default=None, null=True)),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_price_usd', models.DecimalField(decimal_places=2, max_digits=13)),
                ('prefix', models.CharField(blank=True, max_length=25)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('birthyear', models.CharField(blank=True, max_length=10, null=True)),
                ('deathyear', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField()),
                ('aka', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField()),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('artistimage', models.TextField()),
            ],
            options={
                'verbose_name': 'Artwork/Lot/Artist Combined Information Table',
                'db_table': 'fa_artwork_lot_artist',
            },
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artists Information Table'},
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'verbose_name': 'Artworks Information Table'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artworkname',
            field=models.TextField(db_column='faa_artwork_title', db_index=True),
        ),
    ]
